In [70]:
# least square solution(more equations less solutions)
# A(N*M) , W(M*1) , Y(N*1)
# N>M  (NO EXACT SOLUTION)
# Aw=y
# w=inv((A.T).A).(A.T).y

In [71]:
# minimum norm solution(more parameters less equations)
# A(N*M) , W(M*1) , Y(N*1)
# N<M (MANY SOLUTION EXISTS)
# Aw=y
# w=(A.T).inv(A.A.T).y

In [72]:
from sklearn.datasets import load_iris
import numpy as np
import keras
np.random.seed(100)

iris = load_iris()

In [73]:
print('KEYS',iris.keys())
print()

X=iris["data"]
Y=iris["target"]

print(X[:3])
print(Y[:3])


KEYS dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]
[0 0 0]


In [74]:
names=iris["target_names"]
features=iris["feature_names"]

print(names)
print(features)

['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [75]:
isamples = np.random.randint(len(Y) , size=5)
isamples

array([  8,  24,  67, 103,  87])

In [76]:
print(X.shape)
print(Y.shape)

(150, 4)
(150,)


In [77]:
print(X[isamples])
print(Y[isamples])

[[4.4 2.9 1.4 0.2]
 [4.8 3.4 1.9 0.2]
 [5.8 2.7 4.1 1. ]
 [6.3 2.9 5.6 1.8]
 [6.3 2.3 4.4 1.3]]
[0 0 1 2 1]


In [78]:
#one-hot encoding

from keras.utils import to_categorical
ny = len(np.unique(Y))
Y = to_categorical(Y[:] , num_classes=ny)

print(X[isamples])
print(Y[isamples])
print()
print(ny)

[[4.4 2.9 1.4 0.2]
 [4.8 3.4 1.9 0.2]
 [5.8 2.7 4.1 1. ]
 [6.3 2.9 5.6 1.8]
 [6.3 2.3 4.4 1.3]]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

3


In [79]:
#training-testing split

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size=0.2,random_state=1)

In [80]:
#data_normalization

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train) #computes mean and std

X_train=scaler.transform(X_train) #perform transformation
X_test = scaler.transform(X_test)

In [81]:
#defining function to add 1's column

addcol = lambda x: np.concatenate((x,np.ones((x.shape[0],1))),axis=1)

In [82]:
nx,ny=X_train.shape

def findWeights(A,Y):
    
    w = np.linalg.inv(A.T.dot(A)).dot(A.T.dot(Y))
    return w

In [84]:
A = addcol(X_train)
Y = Y_train
w = findWeights(A,Y)
yd = A.dot(w)

In [85]:
def evaluate(y,yd):
    print(confusion_matrix(yd,y))

In [86]:
yd = np.argmax(yd,axis=1)
y = np.argmax(Y,axis=1)
evaluate(y,yd)

[[39  0  0]
 [ 0 22  4]
 [ 0 15 40]]


In [88]:
A = addcol(X_test)
Y = Y_test
w = findWeights(A,Y)
ynew = A.dot(w)

In [89]:
yd = np.argmax(ynew,axis=1)
y = np.argmax(Y,axis=1)
evaluate(y,yd)

[[11  0  0]
 [ 0 13  2]
 [ 0  0  4]]


In [94]:
addSqlcol = lambda x: np.concatenate((x, x**2, np.ones((x.shape[0], 1))), axis = 1)

In [96]:
A = addSqlcol(X_train)
Y = Y_train
w = findWeights(A,Y)
yd = A.dot(w)
yd = np.argmax(yd,axis=1)
y = np.argmax(Y,axis=1)
evaluate(y,yd)

[[39  0  0]
 [ 0 35  2]
 [ 0  2 42]]


In [97]:
A = addSqlcol(X_test)
Y = Y_test
w = findWeights(A,Y)
yd = A.dot(w)
yd = np.argmax(yd,axis=1)
y = np.argmax(Y,axis=1)
evaluate(y,yd)

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
